---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: ngrok
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: nginx-app
                port:
                  number: 80
            pathType: Prefix
            path: /
