{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.widgetfactory.web.servicePort }}
            pathType: Prefix
            path: /
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.widgetfactory.metrics.servicePort }}
            pathType: Prefix
            path: /metrics
{{ end -}}