apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: widget-factory
    component: web-server
spec:
  selector:
    app: widget-factory
    component: web-server
  ports:
    - port: {{ .Values.widgetfactory.web.servicePort }}
      targetPort: {{ .Values.widgetfactory.web.containerPort }}
      name: web
    - port: {{ .Values.widgetfactory.metrics.servicePort }}
      targetPort: {{ .Values.widgetfactory.metrics.containerPort }}
      name: metrics
  type: {{ .Values.widgetfactory.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: widget-factory
    component: database
spec:
  selector:
    app: widget-factory
    component: database-server
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql