apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  serviceName: {{ .Release.Name }}-mysql
  replicas: 1
  selector:
      matchLabels:
        app: widget-factory
        component: database-server
  template:
    metadata:
        labels:
            app: widget-factory
            component: database-server
    spec:
        containers:
        - name: mysql
          image: mysql:5.7
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: {{ .Release.Name}}-mysql
                    key: mysql-root-password
          - name: MYSQL_DATABASE
            value: {{ .Release.Name }}
          ports:
          - containerPort: 3306
          {{- if .Values.database.persistence.enabled }}
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            {{- end }}
    {{- if .Values.database.persistence.enabled }}
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
    {{- end }}