apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  fixedValue: "some important config change that needs to be audited"
  defaultChartValue:  {{ .Values.defaultChartValue }}
  fleetValue: {{ .Values.fleetValue }}
