apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  fixedValue: "declarative from manifest"
  defaultChartValue:  {{ .Values.defaultChartValue }}
  fleetValue: {{ .Values.fleetValue }}
